name: Cron - run alkalinity test

on:
  schedule:
    - cron: "0 16 * * *"


jobs:
  run-alkalinity-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Run cypress
        run: |
          docker run --rm \
                 -e CYPRESS_username=${{ secrets.USERNAME }} \
                 -e CYPRESS_password=${{ secrets.PASSWORD }} \
                 --workdir /e2e \
                 -v "$GITHUB_WORKSPACE":"/e2e" \
                 cypress/included:7.2.0 --spec "cypress/integration/trident-alkalinity.js" --config video=false

