name: Run combined test(Alkalinity, Calcium, Magnesium)

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Input1'
        required: false

#on:
#  push:
#    branches:
#      - master


jobs:
  run-triple-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Run cypress
        run: |
          docker run --rm \
                 -e CYPRESS_username=${{ secrets.USERNAME }} \
                 -e CYPRESS_password=${{ secrets.PASSWORD }} \
                 --workdir /e2e \
                 -v "$GITHUB_WORKSPACE":"/e2e" \
                 cypress/included:7.2.0 --spec "cypress/integration/trident-triple.js"

      - uses: actions/upload-artifact@v2
        with:
          name: trident-triple.js.mp4
          path: ./cypress/videos/trident-triple.js.mp4
