name: Manual run combined test(Alk, Ca, Mg)

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Input1'
        required: false

jobs:
  run-triple-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Check if secrets exist
        run: |
          if [ "${{ secrets.USERNAME2 }}" == "" ]; then
            echo "username secret is not exist or empty"
            echo "please verify it in https://github.com/${{ env.GITHUB_REPOSITORY }}/settings/secrets/actions"
          fi

      - name: Run cypress
        run: |
          docker run --rm \
                 -e CYPRESS_username=${{ secrets.USERNAME }} \
                 -e CYPRESS_password=${{ secrets.PASSWORD }} \
                 --workdir /e2e \
                 -v "$GITHUB_WORKSPACE":"/e2e" \
                 cypress/included:7.2.0 --spec "cypress/integration/trident.js" --config video=false

